name: Salesforce Foundation Technology and Products
url: http://developer.salesforce.org
markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
paginate: 10
paginate_path: ":num"

exclude: [bower_components, node_modules, bower.json, package.json, Gruntfile.js, less]
